services:
  kubernetes-dashboard-token-api:
    container_name: kubernetes-dashboard-token-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /path/to/kubeconfig:/data/config.conf:ro # *required* - Set the target kubeconfig file to use
    ports:
      - 8080:80
    environment:
      - KUBERNETES_DASHBOARD_URL= # Set url here. If no url is provided, no redirection will occur
