name: Docker Containers

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push:
    strategy:
      matrix:
        include:
          - name: Python Project
            context: .
            file: ./Dockerfile
            tag: latest
            image: aidanwallace/kubernetes-dashboard-token-api
            push-requirements: ${{ github.event_name != 'pull_request' && contains(fromJson('["push", "release"]'), github.event_name) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: ${{ matrix.push-requirements }}
          tags: ${{ matrix.image }}:${{ matrix.tag }}

      - name: Was image was pushed
        run: |
          echo "image was pushed: ${{ matrix.push-requirements }}"
