name: Python Test and Lint

on:
  pull_request:
    branches: [main]
    paths:
      - app/**
      - static/**
      - templates/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip -r requirements.txt
          python -m pip install ruff

      - name: Lint with Ruff
        run: ruff check .

      - name: Run tests
        run: pytest --cov
